In [117]:
import pandas as pd
import re
from time import strptime
import time
from datetime import datetime

In [118]:
allData = pd.read_csv("LAHacks Deidentified.csv")

c:\users\norm\appdata\local\programs\python\python37-32\lib\site-packages\IPython\core\interactiveshell.py:3044: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [119]:
allData.head()

,UPC,Category Name,Vendor Name,Receiving Warehouse,Shipping Warehouse,PO,Total Cases,Failed Cases,Inspector,Arrival Date,Shipping Date
0,4.856800e+05,White Cabbages,Vendor 63b9d36c,Warehouse 886ecdf1,Warehouse e5847f7c,248117,385,0,Inspector 4bb23bf2,15-MAR-18,12-MAR-18
1,7.143000e+09,Unassigned,Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,5,0,Inspector c8d7555b,31-AUG-18,30-AUG-18
2,7.143001e+09,Unassigned,Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,10,0,Inspector c8d7555b,31-AUG-18,30-AUG-18
3,7.143001e+09,Unassigned,Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,100,0,Inspector c8d7555b,31-AUG-18,30-AUG-18
4,7.143000e+09,Unassigned,Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,5,0,Inspector c8d7555b,31-AUG-18,30-AUG-18

In [120]:
allData.shape

(227619, 11)

In [121]:
allData= allData[allData['Category Name'] != 'Unassigned']
allData['Month'] = [re.sub(r'[0-9]|-','',x) for x in allData['Shipping Date'].tolist()]
allData['Month'] = [strptime(x, '%b').tm_mon for x in allData['Month'].tolist()]
allData['Day'] = [int(x[0:2]) for x in allData['Shipping Date'].tolist()]
allData['Year'] = [int('20'+str(x[len(x)-2:len(x)])) for x in allData['Shipping Date'].tolist()]

allData.head()

,UPC,Category Name,Vendor Name,Receiving Warehouse,Shipping Warehouse,PO,Total Cases,Failed Cases,Inspector,Arrival Date,Shipping Date,Month,Day,Year
0,4.856800e+05,White Cabbages,Vendor 63b9d36c,Warehouse 886ecdf1,Warehouse e5847f7c,248117,385,0,Inspector 4bb23bf2,15-MAR-18,12-MAR-18,3,12,2018
5,7.143001e+09,Vegetables ? Prepared/Processed (Perishable),Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,15,0,Inspector c8d7555b,31-AUG-18,30-AUG-18,8,30,2018
17,7.143001e+09,Vegetables ? Prepared/Processed (Perishable),Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,20,0,Inspector c8d7555b,31-AUG-18,30-AUG-18,8,30,2018
18,7.143001e+09,Vegetables ? Prepared/Processed (Perishable),Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,15,0,Inspector c8d7555b,31-AUG-18,30-AUG-18,8,30,2018
23,7.143000e+09,Vegetables ? Prepared/Processed (Perishable),Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,2,0,Inspector c8d7555b,31-AUG-18,30-AUG-18,8,30,2018

In [122]:
datetime_arr = [] 
for x in range(len(allData)):
#     print(allData['Year'].iloc[x])
#     print(allData['Month'].iloc[x])
#     print(allData['Day'].iloc[x])
    datetime_arr.append(datetime(allData['Year'].iloc[x], allData['Month'].iloc[x], allData['Day'].iloc[x]))
#allData['datetime'] = allData[['Year','Month', 'Day']].apply(datetime)

In [123]:
allData['datetime'] = datetime_arr
allData['datetime'].iloc[0]
allData = allData.drop(allData.columns[[11, 12, 13]], axis=1)
allData['numeric_datetime'] = [time.mktime(i.timetuple()) for i in allData['datetime']]
allData.head()

,UPC,Category Name,Vendor Name,Receiving Warehouse,Shipping Warehouse,PO,Total Cases,Failed Cases,Inspector,Arrival Date,Shipping Date,datetime,numeric_datetime
0,4.856800e+05,White Cabbages,Vendor 63b9d36c,Warehouse 886ecdf1,Warehouse e5847f7c,248117,385,0,Inspector 4bb23bf2,15-MAR-18,12-MAR-18,2018-03-12,1.520838e+09
5,7.143001e+09,Vegetables ? Prepared/Processed (Perishable),Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,15,0,Inspector c8d7555b,31-AUG-18,30-AUG-18,2018-08-30,1.535612e+09
17,7.143001e+09,Vegetables ? Prepared/Processed (Perishable),Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,20,0,Inspector c8d7555b,31-AUG-18,30-AUG-18,2018-08-30,1.535612e+09
18,7.143001e+09,Vegetables ? Prepared/Processed (Perishable),Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,15,0,Inspector c8d7555b,31-AUG-18,30-AUG-18,2018-08-30,1.535612e+09
23,7.143000e+09,Vegetables ? Prepared/Processed (Perishable),Vendor ee6aa404,Warehouse cb7cd2e2,Warehouse 773064a8,50246763,2,0,Inspector c8d7555b,31-AUG-18,30-AUG-18,2018-08-30,1.535612e+09

### How to use time

In [124]:
# t = datetime.now()
# t1 = t.timetuple()
# secs = time.mktime(t1)
# print (secs)
# print(time.asctime(time.localtime(secs)))